### ISSUE TITLE
泛域名是不是不支持

### ISSUE THREAD

**Issue by lnxyz** [al-one/certbot-auth-dnspod#2]
针对泛域名如这参数： -d laravel.run -d *.laravel.run
这样，dns增加txt, 它只会创建一条_acme-challenge记录。
并另一条报错。
certbot已经对laravel.run 及*.laravel.run产生两组_acme-challenge记录了。
然而真实记录下来只有一条。
合理情况不是这两条记录都创建吗

**Comment by al-one** [comment]
泛解析域名用参数：`-d domain.com -d *.domain.com`

**Comment by lnxyz** [comment]
> 泛解析域名用参数：`-d domain.com -d *.domain.com`
这样是可以了。
