### ISSUE TITLE
首次申请通配符域名时会执行2次脚本导致失败

### ISSUE THREAD

**Issue by whc2001** [al-one/certbot-auth-dnspod#3]
使用时发现申请通配符域名（如test.com和*.test.com）会导致certbot执行2次脚本，_acme_challenge记录只有第二次（最后一次）的内容导致验证失败，但是如果再重新运行一次相同的指令，certbot就只会执行一次脚本，成功申请证书，原因不明

**Comment by whc2001** [comment]
搜了一下，有人提到了这个问题：https://community.letsencrypt.org/t/testing-dns-wildcard-manual-run-challenge-twice/106961
似乎是每一个内容都要追加过去而不是替换，最后cleanup的时候再全删了

**Comment by al-one** [comment]
多谢，已修复
